language: node_js
node_js:
  - 5.0.0
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: 46f6d31d6b0777711b6c7e733234b023bda56e2e02c792c68c889005cf032ea6
install:
  - npm install -g istanbul mocha
  - npm install
script:
  - istanbul cover _mocha
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash cli.sh
  - bash heroku_cli.sh
  - bash sample_deploy.sh
deploy:
  provider: heroku
  api_key:
    secure: vlhKjfHsLuznxAh6q4ZNNkIxqhn+SFCQYJGZSq0S1DXVw8g2v3p02LW22zYAUgZPVyT9yQeOvdXEV+H2A0I/6rvqjgQ5JhNqX64WNLDAZu0mz4JNFnro7Q8Z8HPlEjnM7/t/clTtPvAcy9ZGSVT7eQtTfX32YvM18Te6GZ6JyC4DgdRsmbYrCL3EG1bAyvnWs8b0h9b0YGLF578z05JWONBwu1HFDSvpFpz2oBN7vrIIuAw9TFo6BwZm3oVHnrzrxQR521rlEY1ENGPcGEnkujBozics800t5JPDWZEr5LQM1j0IHYhpR2A24DYYt3Wpxi4JwarOMjgnCP/OcTBzawkKABBLaq6azLaZLFS/Jaeo3X5tukJMzRTI1ZGXLhhpdBGJgmzS/rNMnr4iOdYohCv2GyDsyigj93SHOzOkveBxcIKVp4Lp11YONWMlaW/W0GsuHCOpYYWGbXEYB1TSXFdpatLd+8EeAwR6PeTGaU3z5xfra9q6zQ9Ij5dzJRWfUk2/QxCmGq5/SaU/ArCX0X1ijOrkLd34QvadQunjwQGiNbWiaBDj8sKWhTpTS7De5GTTYTdQN/XP6dsU1nopaULtA/oYq81HhgxjgrbmtpCST/wyr0yuSMKyz/Npvp4HAg9YEYuTIOe9lCYnDdDoZvC/M9w2TK3T4DnpCpPBXbQ=
  app: shubhamopevwebgen
  skip_cleanup: true # this will skip cleaning up assets generated while testing in travis, be sure to delete any extra components you're generating. 
  on:
    repo: shubham-padia/open-event-webapp
    branch:
    - master
    - development